#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xD55D978A8A1420E4 (coreteam@netfilter.org)
#
Name     : libmnl
Version  : 1.0.5
Release  : 21
URL      : https://www.netfilter.org/projects/libmnl/files/libmnl-1.0.5.tar.bz2
Source0  : https://www.netfilter.org/projects/libmnl/files/libmnl-1.0.5.tar.bz2
Source1  : https://www.netfilter.org/projects/libmnl/files/libmnl-1.0.5.tar.bz2.sig
Summary  : Minimalistic Netlink communication library
Group    : Development/Tools
License  : LGPL-2.1
Requires: libmnl-lib = %{version}-%{release}
Requires: libmnl-license = %{version}-%{release}
BuildRequires : doxygen
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : graphviz

%description
= What is libmnl? =
libmnl is a minimalistic user-space library oriented to Netlink developers.
There are a lot of common tasks in parsing, validating, constructing of
both the Netlink header and TLVs that are repetitive and easy to get wrong.
This library aims to provide simple helpers that allows you to re-use code
and to avoid re-inventing the wheel. The main features of this library are:

%package dev
Summary: dev components for the libmnl package.
Group: Development
Requires: libmnl-lib = %{version}-%{release}
Provides: libmnl-devel = %{version}-%{release}
Requires: libmnl = %{version}-%{release}

%description dev
dev components for the libmnl package.


%package dev32
Summary: dev32 components for the libmnl package.
Group: Default
Requires: libmnl-lib32 = %{version}-%{release}
Requires: libmnl-dev = %{version}-%{release}

%description dev32
dev32 components for the libmnl package.


%package lib
Summary: lib components for the libmnl package.
Group: Libraries
Requires: libmnl-license = %{version}-%{release}

%description lib
lib components for the libmnl package.


%package lib32
Summary: lib32 components for the libmnl package.
Group: Default
Requires: libmnl-license = %{version}-%{release}

%description lib32
lib32 components for the libmnl package.


%package license
Summary: license components for the libmnl package.
Group: Default

%description license
license components for the libmnl package.


%prep
%setup -q -n libmnl-1.0.5
cd %{_builddir}/libmnl-1.0.5
pushd ..
cp -a libmnl-1.0.5 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1649176598
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition "
%configure --disable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig:/usr/share/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../build32;
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1649176598
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libmnl
cp %{_builddir}/libmnl-1.0.5/COPYING %{buildroot}/usr/share/package-licenses/libmnl/01a6b4bf79aca9b556822601186afab86e8c4fbf
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
if [ -d %{buildroot}/usr/share/pkgconfig ]
then
pushd %{buildroot}/usr/share/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libmnl/libmnl.h
/usr/lib64/libmnl.so
/usr/lib64/pkgconfig/libmnl.pc
/usr/share/man/man3/mnl_attr_get_len.3
/usr/share/man/man3/mnl_attr_get_payload.3
/usr/share/man/man3/mnl_attr_get_payload_len.3
/usr/share/man/man3/mnl_attr_get_str.3
/usr/share/man/man3/mnl_attr_get_type.3
/usr/share/man/man3/mnl_attr_get_u16.3
/usr/share/man/man3/mnl_attr_get_u32.3
/usr/share/man/man3/mnl_attr_get_u64.3
/usr/share/man/man3/mnl_attr_get_u8.3
/usr/share/man/man3/mnl_attr_nest_cancel.3
/usr/share/man/man3/mnl_attr_nest_end.3
/usr/share/man/man3/mnl_attr_nest_start.3
/usr/share/man/man3/mnl_attr_nest_start_check.3
/usr/share/man/man3/mnl_attr_next.3
/usr/share/man/man3/mnl_attr_ok.3
/usr/share/man/man3/mnl_attr_parse.3
/usr/share/man/man3/mnl_attr_parse_nested.3
/usr/share/man/man3/mnl_attr_parse_payload.3
/usr/share/man/man3/mnl_attr_put.3
/usr/share/man/man3/mnl_attr_put_check.3
/usr/share/man/man3/mnl_attr_put_str.3
/usr/share/man/man3/mnl_attr_put_str_check.3
/usr/share/man/man3/mnl_attr_put_strz.3
/usr/share/man/man3/mnl_attr_put_strz_check.3
/usr/share/man/man3/mnl_attr_put_u16.3
/usr/share/man/man3/mnl_attr_put_u16_check.3
/usr/share/man/man3/mnl_attr_put_u32.3
/usr/share/man/man3/mnl_attr_put_u32_check.3
/usr/share/man/man3/mnl_attr_put_u64.3
/usr/share/man/man3/mnl_attr_put_u64_check.3
/usr/share/man/man3/mnl_attr_put_u8.3
/usr/share/man/man3/mnl_attr_put_u8_check.3
/usr/share/man/man3/mnl_attr_type_valid.3
/usr/share/man/man3/mnl_attr_validate.3
/usr/share/man/man3/mnl_attr_validate2.3
/usr/share/man/man3/mnl_cb_run.3
/usr/share/man/man3/mnl_cb_run2.3
/usr/share/man/man3/mnl_nlmsg_batch_current.3
/usr/share/man/man3/mnl_nlmsg_batch_head.3
/usr/share/man/man3/mnl_nlmsg_batch_is_empty.3
/usr/share/man/man3/mnl_nlmsg_batch_next.3
/usr/share/man/man3/mnl_nlmsg_batch_reset.3
/usr/share/man/man3/mnl_nlmsg_batch_size.3
/usr/share/man/man3/mnl_nlmsg_batch_start.3
/usr/share/man/man3/mnl_nlmsg_batch_stop.3
/usr/share/man/man3/mnl_nlmsg_fprintf.3
/usr/share/man/man3/mnl_nlmsg_get_payload.3
/usr/share/man/man3/mnl_nlmsg_get_payload_len.3
/usr/share/man/man3/mnl_nlmsg_get_payload_offset.3
/usr/share/man/man3/mnl_nlmsg_get_payload_tail.3
/usr/share/man/man3/mnl_nlmsg_next.3
/usr/share/man/man3/mnl_nlmsg_ok.3
/usr/share/man/man3/mnl_nlmsg_portid_ok.3
/usr/share/man/man3/mnl_nlmsg_put_extra_header.3
/usr/share/man/man3/mnl_nlmsg_put_header.3
/usr/share/man/man3/mnl_nlmsg_seq_ok.3
/usr/share/man/man3/mnl_nlmsg_size.3
/usr/share/man/man3/mnl_socket_bind.3
/usr/share/man/man3/mnl_socket_close.3
/usr/share/man/man3/mnl_socket_fdopen.3
/usr/share/man/man3/mnl_socket_get_fd.3
/usr/share/man/man3/mnl_socket_get_portid.3
/usr/share/man/man3/mnl_socket_getsockopt.3
/usr/share/man/man3/mnl_socket_open.3
/usr/share/man/man3/mnl_socket_open2.3
/usr/share/man/man3/mnl_socket_recvfrom.3
/usr/share/man/man3/mnl_socket_sendto.3
/usr/share/man/man3/mnl_socket_setsockopt.3

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libmnl.so
/usr/lib32/pkgconfig/32libmnl.pc
/usr/lib32/pkgconfig/libmnl.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmnl.so.0
/usr/lib64/libmnl.so.0.2.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libmnl.so.0
/usr/lib32/libmnl.so.0.2.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libmnl/01a6b4bf79aca9b556822601186afab86e8c4fbf
