#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xAB4655A126D292E4 (coreteam@netfilter.org)
#
Name     : libmnl
Version  : 1.0.4
Release  : 13
URL      : https://www.netfilter.org/projects/libmnl/files/libmnl-1.0.4.tar.bz2
Source0  : https://www.netfilter.org/projects/libmnl/files/libmnl-1.0.4.tar.bz2
Source99 : https://www.netfilter.org/projects/libmnl/files/libmnl-1.0.4.tar.bz2.sig
Summary  : Minimalistic Netlink communication library
Group    : Development/Tools
License  : LGPL-2.1
Requires: libmnl-lib
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32

%description
= What is libmnl? =
libmnl is a minimalistic user-space library oriented to Netlink developers.
There are a lot of common tasks in parsing, validating, constructing of
both the Netlink header and TLVs that are repetitive and easy to get wrong.
This library aims to provide simple helpers that allows you to re-use code
and to avoid re-inventing the wheel. The main features of this library are:

%package dev
Summary: dev components for the libmnl package.
Group: Development
Requires: libmnl-lib
Provides: libmnl-devel

%description dev
dev components for the libmnl package.


%package dev32
Summary: dev32 components for the libmnl package.
Group: Default
Requires: libmnl-lib32
Requires: libmnl-dev

%description dev32
dev32 components for the libmnl package.


%package lib
Summary: lib components for the libmnl package.
Group: Libraries

%description lib
lib components for the libmnl package.


%package lib32
Summary: lib32 components for the libmnl package.
Group: Default

%description lib32
lib32 components for the libmnl package.


%prep
%setup -q -n libmnl-1.0.4
pushd ..
cp -a libmnl-1.0.4 build32
popd

%build
export LANG=C
export SOURCE_DATE_EPOCH=1492120833
%configure --disable-static
make V=1  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make V=1  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1492120833
rm -rf %{buildroot}
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libmnl/libmnl.h
/usr/lib64/libmnl.so
/usr/lib64/pkgconfig/libmnl.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libmnl.so
/usr/lib32/pkgconfig/32libmnl.pc
/usr/lib32/pkgconfig/libmnl.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmnl.so.0
/usr/lib64/libmnl.so.0.2.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libmnl.so.0
/usr/lib32/libmnl.so.0.2.0
